WRC-CMS/Controllers/AddViewController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WRC_CMS.Communication;
using WRC_CMS.Models;
using WRC_CMS.Repository;

namespace WRC_CMS.Controllers
{
    public class AddViewController : BaseController
    {
        public WebApiProxy proxy = new WebApiProxy();

        public async Task<JsonResult> AddUpdateRecord(ViewModel ModelObject)
        {
            string Status = string.Empty;
            List<ViewModel> views = new List<ViewModel>();
            await Task.Run(() =>
                {
                    Status = base.BaseAddUpdateRecord(ModelObject, ModelState, proxy).Result;
                    views.AddRange(BORepository.GetAllViews(proxy, ModelObject.SiteID).Result);
                }
            );
            return Json(new { status = views, JsonRequestBehavior.AllowGet });
        }

        public async Task<ActionResult> EditViewDetails(int ViewID = 0, int SiteID = 0)
        {
            if (ViewID != 0)
            {
                CombineModel com = null;
                string TableBody = string.Empty;
                await Task.Run(() =>
                 {
                     com = GetCombineModel(ViewID, SiteID).Result;
                 });

                await Task.Run(() =>
                 {
                     TableBody = DrawTableBody(ViewID, SiteID).Result;
                 });
                return Json(new { status = com, tablebody = TableBody });
                //return View("ViewsLV", com);               
            }
            else
                return RedirectToAction("GetAllViewDetails", new { id = SiteID });
        }

        private async Task<CombineModel> GetCombineModel(int ViewID = 0, int SiteID = 0)
        {
            CombineModel com = new CombineModel();
            List<ViewModel> views = new List<ViewModel>();
            await Task.Run(() =>
            {
                views.AddRange(BORepository.GetAllViews(proxy, SiteID).Result);
            });
            com.NewView = views.FirstOrDefault(view => view.Oid == ViewID);
            await Task.Run(() =>
           {
               var IsMenuExist = BORepository.GetAllMenu(proxy, SiteID).Result.FirstOrDefault(item => item.ViewId == ViewID);
               if (!ReferenceEquals(IsMenuExist, null))
                   com.NewView.CreateMenu = true;
           });
            com.views = views;
            if (views.Count > 0)
            {
                com.SiteName = views[0].SelectSite;
                com.SiteID = views[0].SiteID;
            }
            ViewBag.CurrSiteID = SiteID;

            await Task.Run(() =>
            {
                com.ViewAllContents.AddRange(BORepository.GetAllContents(proxy, com.SiteID).Result.ToList());
            });

            await Task.Run(() =>
            {
                com.ViewContents.AddRange(BORepository.GetAllContents(proxy, com.SiteID, com.NewView.Oid).Result.ToList());
            });

            return com;
        }

        public async Task<ActionResult> DeleteView(int ViewID, bool IsDefault, int SiteID)
        {
            if (!IsDefault)
            {
                Dictionary<string, object> dicParams = new Dictionary<string, object>();
                dicParams.Add("@Id", ViewID);
                proxy.ExecuteNonQuery("SP_ViewDel", dicParams);
            }
            else
                ViewData["DeletionError"] = "Problem occured while deleting view.Cannot delete Default View.";

            ActionResult View = null;
            await Task.Run(() =>
            {
                View = ReturnToMainView(SiteID).Result;
            });
            return View;
        }

        public async Task<JsonResult> AddViewContent(int contentId, int viewId, int siteId)
        {
            Dictionary<string, object> dicParams = new Dictionary<string, object>();
            dicParams.Add("@Id", -1);
            dicParams.Add("@Order", 0);
            dicParams.Add("@ContentId", contentId);
            dicParams.Add("@ViewId", viewId);
            dicParams.Add("@SiteId", siteId);

            proxy.ExecuteNonQuery("SP_ContentOfViewAddUp", dicParams);

            string tabelBody = await DrawTableBody(viewId, siteId);
            return Json(new { Result = tabelBody });
        }

        private async Task<string> DrawTableBody(int viewId, int siteId)
        {
            StringBuilder tableBody = new StringBuilder();

            var combineModel = await GetCombineModel(viewId, siteId);
            if (combineModel != null)
            {
                var viewContents = combineModel.ViewContents;

                tableBody.AppendLine("<thead _ngcontent-xlf-80='' class='thead-custom-style approvals-card'>");
                tableBody.AppendLine("    <tr _ngcontent-xlf-80=''>");
                tableBody.AppendLine("       <th _ngcontent-xlf-80='' class='col-width-20' data-field='date'>Order</th>");
                tableBody.AppendLine("        <th _ngcontent-xlf-80='' class='col-width-20' data-field='comments'>Name</th>");
                tableBody.AppendLine("        <th _ngcontent-xlf-80='' class='col-width-20' data-field='comments'>Orientation</th>");
                tableBody.AppendLine("        <th _ngcontent-xlf-80='' class='col-width-20' data-field='comments'>Delete</th>");
                tableBody.AppendLine("       <th _ngcontent-xlf-80='' class='col-width-20' data-field='comments'>Move Up-Down</th>");
                tableBody.AppendLine("    </tr>");
                tableBody.AppendLine("</thead>");
                tableBody.AppendLine("<tbody _ngcontent-xlf-80='' class='leave-tbody'>");
                foreach (var item in viewContents)
                {
                    tableBody.AppendLine("<tr _ngcontent-xlf-80='' class='requiredRow'>");
                    tableBody.AppendLine("  <td _ngcontent-xlf-80='' class='col-width-20 orderNo'>");
                    tableBody.AppendLine(item.Order.ToString());
                    tableBody.AppendLine("</td>");
                    tableBody.AppendLine("<td _ngcontent-xlf-80='' class='col-width-20'>");
                    tableBody.AppendLine(item.Name);
                    tableBody.AppendLine("</td>");
                    tableBody.AppendLine("<td _ngcontent-xlf-80='' class='col-width-20'>");
                    tableBody.AppendLine(item.Orientation.ToString());
                    tableBody.AppendLine("</td>");
                    tableBody.AppendLine("<td _ngcontent-xlf-80='' class='col-width-20'>");
                    tableBody.AppendLine(string.Format("<a href='/AddView/DeleteViewContent/{0}?siteId={1}&viewId={2}' onclick='return confirm('Are sure wants to delete?');'>Delete</a>", item.Id, item.SiteID, item.ViewID));
                    tableBody.AppendLine("</td>");
                    tableBody.AppendLine("<td _ngcontent-xlf-80='' class='col-width-20'>");
                    tableBody.AppendLine(string.Format("        <input type='submit' value='Λ' class='' id='btUp' onclick='OnBtnUpClick({0}, true);' {1}/> | ", item.Id, DisabledAction(item.IsUp)));
                    tableBody.AppendLine(string.Format("        <input type='submit' value='V' class='' id='btDown' onclick='OnBtnUpClick({0}, false);' {1}/>", item.Id, DisabledAction(item.IsDown)));
                    tableBody.AppendLine("  </td>");
                    tableBody.AppendLine("</tr>");
                }
                tableBody.AppendLine("</tbody>");
            }
            return tableBody.ToString();
        }
        string DisabledAction(bool isDisabled)
        {
            if (isDisabled)
                return " disabled='disabled'";
            return string.Empty;
        }

        public ActionResult DeleteViewContent(int id, int siteId, int viewId)
        {
            try
            {
                Dictionary<string, object> dicParams = new Dictionary<string, object>();
                dicParams.Add("@Id", id);
                proxy.ExecuteNonQuery("SP_ViewContentsDel", dicParams);
                ModelState.Clear();
                return RedirectToAction("EditViewDetails", new { ViewID = viewId, SiteId = siteId });
            }
            catch
            {
                return View();
            }
        }

        public async Task<JsonResult> RecordMoveUpAndDown(int id, int viewId, int siteId, bool isUpOrDown)
        {
            Dictionary<string, object> dicParams = new Dictionary<string, object>();
            dicParams.Add("@Id", id);
            dicParams.Add("@ViewId", viewId);
            dicParams.Add("@SiteId", siteId);
            if (isUpOrDown)
                dicParams.Add("@MoveUp", -1);
            else
                dicParams.Add("@MoveUp", 1);

            proxy.ExecuteNonQuery("SP_ViewContentUpDown", dicParams);

            string tabelBody = await DrawTableBody(viewId, siteId);
            return Json(new { Result = tabelBody });
        }

        public async Task<ActionResult> ReturnToMainView(int id)
        {
            List<ViewModel> views = new List<ViewModel>();
            await Task.Run(() =>
            {
                views.AddRange(BORepository.GetAllViews(proxy, id).Result);
            });
            CombineModel com = new CombineModel();
            com.NewView = new ViewModel();
            com.views = views;
            if (views.Count > 0)
            {
                com.SiteName = views[0].SelectSite;
                com.SiteID = views[0].SiteID;
            }
            ViewBag.CurrSiteID = id;

            await Task.Run(() =>
            {
                com.ViewAllContents.AddRange(BORepository.GetAllContents(proxy, com.SiteID, true).Result.ToList());
            });

            await Task.Run(() =>
                {
                    com.ViewContents.AddRange(BORepository.GetAllContents(proxy, com.SiteID, com.NewView.Oid).Result.ToList());
                });

WRC-CMS/Views/AddView/AddView.cshtml
@model WRC_CMS.Models.ViewModel


<form name="datapluspics" method="Post" enctype="multipart/form-data">
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @*<h4>Add View</h4>
            <hr />*@
        @Html.ValidationSummary(true)

        @*<div class="form-group">
                @Html.LabelFor(model => model.SelectSite, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.SelectSite, new SelectList(Model.Site, "Oid", "Name", null))
                    @Html.ValidationMessageFor(model => model.SelectSite)
                </div>
            </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.URL, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.URL)
                @Html.ValidationMessageFor(model => model.URL)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Logo, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.TextBoxFor(model => model.Logo, new { type = "file"} )*@
                <input type="file" name="file" />
                @Html.ValidationMessageFor(model => model.Logo)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsActive)
                @Html.ValidationMessageFor(model => model.IsActive)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDefault, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsDefault)
                @Html.ValidationMessageFor(model => model.IsDefault)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Authorized, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Authorized)
                @Html.ValidationMessageFor(model => model.Authorized)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateMenu, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateMenu)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
                @Html.ActionLink("Save", "AddView1", new { Name = Model.Name })
                @Html.ActionLink("Edit", "EditViewDetails", new { id = Model.Name })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10" style="color:green">
                @ViewBag.Message
            </div>
        </div>
    </div>
</form>

<div>
    @*@Html.ActionLink("Back to List", "GetAllViewDetails")*@
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WRC-CMS/Views/AddView/EditViewDetails.cshtml
@model WRC_CMS.Models.ViewModel


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Edit View</h4>
        <hr />
        @Html.ValidationSummary(true)
        <div class="form-group" hidden="hidden">
            @Html.LabelFor(model => model.Oid, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Oid)
                @Html.ValidationMessageFor(model => model.Oid)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SelectSite, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.SelectSite, new SelectList(Model.Site, "Oid", "Name", null))
                @Html.ValidationMessageFor(model => model.SelectSite)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.URL, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.URL)
                @Html.ValidationMessageFor(model => model.URL)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsActive)
                @Html.ValidationMessageFor(model => model.IsActive)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsDefault, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsDefault)
                @Html.ValidationMessageFor(model => model.IsDefault)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Authorized, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Authorized)
                @Html.ValidationMessageFor(model => model.Authorized)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateMenu, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateMenu)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WRC-CMS/Views/AddView/GetViewDetails.cshtml
@model IEnumerable<WRC_CMS.Models.ViewModel>

<p>
    @Html.ActionLink("Create New", "AddView")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.SelectSite)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.URL)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsDefault)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Authorized)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreateMenu)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.SelectSite)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.URL)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsActive)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsDefault)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Authorized)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreateMenu)
            </td>
            <td>
                @Html.ActionLink("Edit", "EditViewDetails", new { id = item.Oid }) |
                @Html.ActionLink("Delete", "DeleteView", new { id = item.Oid }, new { onclick = "return confirm('This will also delete all Contents belongs to this site, Are sure wants to delete?');" })
            </td>
        </tr>
    }

</table>k