WRC-CMS/Controllers/BulkDataController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WRC_CMS.Communication;
using WRC_CMS.Models;
using WRC_CMS.Repository;

namespace WRC_CMS.Controllers
{
    public class BulkDataController : Controller
    {
        WebApiProxy proxy = new WebApiProxy();
        public ActionResult BulkData()
        {
            return View();
        }

        [HttpPost]
        public ActionResult BulkData(string commandName, BulkDataModel bulkDataModel)
        {
            try
            {
                if (ModelState.IsValid && bulkDataModel != null && bulkDataModel.NoOfRecords != 0)
                {
                    if (Request.Form["bt1"] != null)
                    {
                        CreateSites(bulkDataModel.NoOfRecords);
                    }
                    else if (Request.Form["bt2"] != null)
                    {
                        CreateViews(bulkDataModel.NoOfRecords);
                    }
                    else if (Request.Form["bt3"] != null)
                    {
                        CreateStaticContent(bulkDataModel.NoOfRecords);
                    }
                    else if (Request.Form["bt4"] != null)
                    {
                        CreateStaticMenu(bulkDataModel.NoOfRecords);
                    }
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        void CreateSites(int noOfRecords)
        {
            for (int i = 0; i < noOfRecords; i++)
            {
                Dictionary<string, object> dicParams = new Dictionary<string, object>();
                dicParams.Add("@Id", -1);
                dicParams.Add("@Name", MockData.Company.Name());
                dicParams.Add("@url", MockData.Internet.DomainName());
                dicParams.Add("@Logo", new ComplexDataModel(typeof(Byte[]), CommonClass.GetImage(Server.MapPath(@"..\Images\bb.jpg"))));
                dicParams.Add("@Title", MockData.Product.ProductName());
                dicParams.Add("@IsActive", MockData.RandomNumber.Next(0, 1));

                proxy.ExecuteNonQuery("SP_SiteAddUp", dicParams);
            }
        }

        void CreateViews(int noOfRecords)
        {
            for (int i = 0; i < noOfRecords; i++)
            {
                Dictionary<string, object> dicParams = new Dictionary<string, object>();
                dicParams.Add("@Id", -1);
                dicParams.Add("@Name", MockData.Company.Name());
                dicParams.Add("@url", MockData.Internet.DomainName());
                dicParams.Add("@Logo", CommonClass.GetImage(""));
                dicParams.Add("@Title", MockData.Product.ProductName());
                dicParams.Add("@IsActive", MockData.RandomNumber.Next(0, 1));
                dicParams.Add("@Authorized", MockData.RandomNumber.Next(0, 1));
                dicParams.Add("@IsDefault", MockData.RandomNumber.Next(0, 1));
                dicParams.Add("@IsMenu", MockData.RandomNumber.Next(0, 1));

                proxy.ExecuteNonQuery("SP_ViewAddUp", dicParams);
            }
        }

        void CreateStaticContent(int noOfRecords)
        {
            for (int i = 0; i < noOfRecords; i++)
            {
                Dictionary<string, object> dicParams = new Dictionary<string, object>();

                dicParams.Add("@Id", -1);
                dicParams.Add("@Views", MockData.RandomNumber.Next(0, GetMaxNumber("Views")));
                dicParams.Add("@Name", MockData.Company.Name());
                dicParams.Add("@Descr", MockData.Address.SecondaryAddress());
                dicParams.Add("@IsActive", MockData.RandomNumber.Next(0, 1));
                proxy.ExecuteNonQuery("SP_ContentsAddUp", dicParams);
            }
        }

        void CreateStaticMenu(int noOfRecords)
        {

        }

        int GetMaxNumber(string type)
        {
            return 1;
        }
    }
}

WRC-CMS/Controllers/SiteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Security.Policy;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WRC_CMS.Communication;
using WRC_CMS.Models;
using WRC_CMS.Repository;



using Newtonsoft.Json;
using System.IO;
namespace WRC_CMS.Controllers
{
    public class SiteController : Controller
    {
        WebApiProxy proxy = new WebApiProxy();
        public ActionResult AddSite()
        {

            return View();
        }

        public async Task<ActionResult> PreviewSite(int id)
        {
            List<SiteModel> sites = new List<SiteModel>();
            List<ViewModel> views = new List<ViewModel>();
            await Task.Run(() =>
            {
                sites.AddRange(BORepository.GetAllSites(proxy, id).Result);
            });
            await Task.Run(() =>
            {
                views.AddRange(BORepository.GetAllViews(proxy, id).Result);
            });
            if (sites != null && sites.Count > 0)
            {
                SiteModel objetc = sites.FirstOrDefault(item => item.Oid == id);
                if (views != null && views.Count > 0)
                {
                    objetc.ViewList = new List<ViewModel>();
                    objetc.ViewList.AddRange(views.Where(items => items.SiteID == objetc.Oid));
                }
                return View("PreviewSite", objetc);
            }
            return View();
        }

        public async Task<ActionResult> ShowViewContent(int SiteID, int ViewID)
        {
            List<SiteModel> sites = new List<SiteModel>();
            List<ViewModel> views = new List<ViewModel>();
            List<ContentStyleModel> contents = new List<ContentStyleModel>();
            await Task.Run(() =>
            {
                sites.AddRange(BORepository.GetAllSites(proxy, SiteID).Result);
            });
            await Task.Run(() =>
            {
                views.AddRange(BORepository.GetAllViews(proxy, SiteID).Result);
            });
            if (sites != null && sites.Count > 0)
            {
                SiteModel objetc = sites.FirstOrDefault(item => item.Oid == SiteID);
                if (views != null && views.Count > 0)
                {
                    objetc.ViewList = new List<ViewModel>();
                    objetc.ViewList.AddRange(views.Where(items => items.SiteID == objetc.Oid));
                    var SelectetdView = objetc.ViewList.FirstOrDefault(ite => ite.Oid == ViewID);
                    if (!ReferenceEquals(SelectetdView, null))
                    {
                        await Task.Run(() =>
                        {
                            //contents.AddRange(BORepository.GetAllContents(proxy).Result);
                        });
                        SelectetdView.Contents = new List<ContentStyleModel>();
                        SelectetdView.Contents.AddRange(contents.Where(ite => ite.ViewID == ViewID));
                        if (SelectetdView.Contents != null && SelectetdView.Contents.Count > 0)
                        {
                            StringBuilder strb = new StringBuilder();
                            foreach (var cont in SelectetdView.Contents)
                            {
                                strb.AppendLine(cont.Description);
                            }
                            ViewBag.Message = strb.ToString();
                        }
                    }
                }
                return View("PreviewSite", objetc);
            }
            return View();
        }

        //public JsonResult SiteExists(string Name)
        //{
        //    var user = Name;
        //    return user == null ?
        //        Json(true, JsonRequestBehavior.AllowGet) :
        //        Json(string.Format("{0} Already Exist.", Name),
        //            JsonRequestBehavior.AllowGet);
        //}


        //        [HttpPost]
        //        public async Task<ActionResult> AddSite(SiteModel SiteObject, HttpPostedFileBase file)
        //        {
        //            try
        //            {
        //                if (file != null && file.ContentLength > 0)
        //                {
        //                    SiteObject.Logo = new byte[file.ContentLength];
        //                    file.InputStream.Read(SiteObject.Logo, 0, file.ContentLength);
        //                }
        //                if (ModelState.IsValid)
        //                {
        //                    Dictionary<string, object> dicParams = new Dictionary<string, object>();
        //                    dicParams.Add("@Id", -1);
        //                    dicParams.Add("@Name", SiteObject.Name);
        //                    dicParams.Add("@url", SiteObject.URL);
        //                    dicParams.Add("@Logo", 0101);
        //                    dicParams.Add("@Title", SiteObject.Title);
        //                    if (SiteObject.IsActive)
        //                        dicParams.Add("@IsActive", "1");
        //                    else
        //                        dicParams.Add("@IsActive", "0");
        //                    DataSet dataSet = null;
        //                    await Task.Run(() =>
        //                    {
        //                        dataSet = proxy.ExecuteDataset("SP_SiteAddUp", dicParams).Result;
        //                    });

        //                    int SiteID = 0;
        //                    if (dataSet != null && dataSet.Tables != null && dataSet.Tables.Count > 0)
        //                    {
        //                        if (dataSet.Tables[0].Rows != null && dataSet.Tables[0].Rows.Count > 0)
        //                        {
        //                            SiteID = Convert.ToInt32(dataSet.Tables[0].Rows[0][0].ToString());

        //                            ViewModel DefaultView = new ViewModel();
        //                            DefaultView.Name = "Home";

        //                            DefaultView.Title = "Home";
        //                            DefaultView.IsActive = true;
        //                            DefaultView.IsDefault = true;
        //                            DefaultView.Authorized = true;
        //                            DefaultView.SiteID = SiteID;
        //                            DefaultView.CreateMenu = true;
        //                            DefaultView.IsDefault = true;
        //                            int ViewID = 0;
        //                            await Task.Run(() =>
        //                            {
        //                                ViewID = BORepository.AddView(proxy, DefaultView, true).Result;
        //                            });
        //                            if (ViewID > 0)
        //                            {
        //                                ContentStyleModel DefaultContent = new ContentStyleModel();
        //                                DefaultContent.Name = "Welcome";
        //                                string welcomebody = @"<p><span style='font-size: medium;'><b><span style='text-decoration: underline;'>This is our default template.</span></b></span></p>
        //<p><strong><span style='text-decoration: underline;'>Welcome to our site.<img src='http://localhost:49791/Scripts/tinymce/plugins/emotions/img/smiley-smile.gif' alt='Smile' title='Smile' border='0' /></span></strong></p>";
        //                                DefaultContent.Description = welcomebody;

        //                                DefaultContent.IsActive = true;
        //                                DefaultContent.ViewID = ViewID;
        //                                DefaultContent.IsDefault = true;
        //                                int ContentID = 0;
        //                                await Task.Run(() =>
        //                                {
        //                                    ContentID = BORepository.AddContentStyle(proxy, DefaultContent).Result;
        //                                });
        //                            }
        //                        }
        //                    }
        //                    if (SiteID != 0)
        //                        ViewBag.Message = "Site added successfully.";
        //                    else
        //                        ViewBag.Message = "Problem occured while creating site, kindly contact our support team.";
        //                }
        //                return View();
        //            }
        //            catch
        //            {
        //                return View();
        //            }
        //        }

        [HttpPost]
        public ActionResult EditSiteDetails(SiteModel SiteObject, HttpPostedFileBase file)
        {
            try
            {
                if (file != null && file.ContentLength > 0)
                {
                    SiteObject.Logo = new byte[file.ContentLength];
                    file.InputStream.Read(SiteObject.Logo, 0, file.ContentLength);
                }
                if (ModelState.IsValid)
                {
                    Dictionary<string, object> dicParams = new Dictionary<string, object>();
                    dicParams.Add("@Id", SiteObject.Oid);
                    dicParams.Add("@Name", SiteObject.Name);
                    dicParams.Add("@url", SiteObject.URL);
                    dicParams.Add("@Logo", CommonClass.GetImage(file.InputStream));
                    dicParams.Add("@Title", SiteObject.Title);
                    if (SiteObject.IsActive)
                        dicParams.Add("@IsActive", "1");
                    else
                        dicParams.Add("@IsActive", "0");
                    proxy.ExecuteNonQuery("SP_SiteAddUp", dicParams);

WRC-CMS/Views/Shared/_AdminPanel.cshtml
@using Microsoft.AspNet.Identity
<div class="row">
    <div class="row  col-md-5">
        <div id="sidebar" class="col-md-4">
            <ul>
                <li>@Html.ActionLink("Sites", "AddSite", "Site")</li>
                <li>@Html.ActionLink("Views", "AddView", "AddView")</li>
                <li>@Html.ActionLink("Content Styles", "AddContentStyle", "ContentStyle")</li>
            </ul>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - WRC-CMS</p>
            </footer>
        </div>
    </div>
</div>
<div>
    @Html.ActionLink("Home Page", "Dashboard", "Site")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WRC-CMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - WRC-CMS Application</title>
    @Styles.Render("~/Content/css")
    @*@Scripts.Render("~/bundles/modernizr")*@

</head>

<body>
    <div class="attendance-main attendance-main-inverse attendance-main-fixed-top">
        @RenderBody()
        @*<div class="navbar navbar-inverse navbar-fixed-top">
                            <div class="container">
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-

            target=".navbar-collapse">
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                    @Html.ActionLink("WRC-CMS", "Index", "Home", null, new { @class = "navbar-

            brand" })
                                </div>
                                <div class="navbar-collapse collapse">
                                    <ul class="nav navbar-nav">
                                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                                        <li>@Html.ActionLink("Sites", "GetAllSitesDetails", "Site")</li>
                                        <li>@Html.ActionLink("Views", "GetAllViewDetails", "AddView")</li>
                                        <li>@Html.ActionLink("Content Styles", "GetAllContentsDetails",

            "ContentStyle")</li>
                                        <li>@Html.ActionLink("Bulk Data", "BulkData", "BulkData")</li>
                                    </ul>
                                    @Html.Partial("_LoginPartial")
                                </div>
                            </div>
                        </div>*@
        <div>
            @*@Html.Partial("AddView", new WRC_CMS.Models.ViewModel());*@
            @*@RenderBody()*@
            @*<hr />*@
            @*<footer>
                    <p>&copy; @DateTime.Now.Year - WRC-CMS</p>
                </footer>*@
        </div>
    </div>
    <footer class="page-footer">
        <div class="row footer-copyright m-bottom0">
            <div class="col s6 m6 l6 right-align m-top20 branding">
                © 2016 V2Solutions, Inc.
            </div>
            @*<div class="col s6 m6 l6 right-align" id="browsers">
                    <ul class="right">
                        <li>
                            <i aria-hidden="true" class="fa fa-chrome"></i>
                            <h6 class="margin-zero">Ver 50+</h6>
                        </li>
                        <li>
                            <i aria-hidden="true" class="fa fa-firefox"></i>
                            <h6 class="margin-zero">Ver 46+ (64-bit)</h6>
                        </li>
                        <li>
                            <i aria-hidden="true" class="fa fa-safari"></i>
                            <h6 class="margin-zero">Ver 10+</h6>
                        </li>
                    </ul>
                </div>*@
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>